### ISSUE TITLE
tweet.field text is truncated - how to get full text?

### ISSUE THREAD

**Issue by rdupz** [twitterdev/twitter-api-typescript-sdk#35]
Hello,

I would like to know if it's possible to get full text when asking for the text?

Here is what I tried after googling a bit.

```
    const stream = client.tweets.searchStream({
        "tweet.fields": ["id", "text", "entities"],
    }, {
        params: {
            "tweet_mode": "extended",
        }
    });
```

I'm probably missing something.

Best regards,

**Comment by andypiper** [comment]
`tweet_mode` is not a parameter in v2 of the API, since the API treats 280 characters as the default possible length for Tweet text.

It sounds like you may be getting Retweets or quoted Tweets? If so, you may need to request the `referenced_tweets` expansion. If you have the ID of a Tweet where you're seeing the truncated text, you could try using the [API Playground](https://oauth-playground.glitch.me/?id=findTweetById&params=%28%27id%21%271552970423004012544%27%7Eexpansions%21%27referenced_tweets.id%27%29_) to test out the various parameters.

**Comment by rdupz** [comment]
That was a rt, thanks!
